# Generated by Django 2.1.5 on 2021-03-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=198)),
                ('email', models.EmailField(max_length=254)),
                ('consulta', models.TextField()),
                ('telefono', models.IntegerField(blank=True, help_text='Contact phone number')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
