# Generated by Django 2.1.5 on 2021-03-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='telefono',
            new_name='Whatsapp',
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha_de_creacion',
            field=models.DateField(auto_now=True, verbose_name='fecha de creacion'),
        ),
    ]
